import { string } from 'yup/lib/locale';

export type RootStackParamList = {
  Home: undefined;
  MyPage: undefined;
  Lobby: undefined;
  TeamSelect: undefined;
  CreateTeam: undefined;
  CreateTeam_1: undefined;
  CreateTeam_2: undefined;
  CreateTeam_3: undefined | { bank: string };
  CreateTeam_4: undefined;
  CreateTeam_5: undefined;
  CreateTeam_6: undefined;
  BankSelect: undefined;
  LendingPage: undefined;
  LendingPage_1: undefined;
  LendingPage_2: undefined;
  LendingPage_3: undefined;
  LendingPage_4: undefined;
  LendingPage_5: undefined;
  LendingPage_6: undefined;
  LendingPage_7: undefined;
  LendingPage_8: undefined;
  JoinTeam: undefined;
  JoinTeam_1: undefined | { reset: boolean };
  JoinTeam_2: undefined;
  JoinTeam_3: undefined;
  GetStarted: undefined;
  GetStarted_1: undefined;
  GetStarted_2: undefined;
  GetStarted_3: undefined | { phone: string };
  GetStarted_4: undefined;
  GetStarted_5: undefined | { gender: string };
  GetStarted_6: undefined;
  GenderSelect: undefined | { screenName: keyof RootStackParamList };
  GetStarted_Login: undefined | { email: string };
  FindPassword: undefined;
  FindPassword_1: undefined;
  FindPassword_2: undefined;
  ScheduleManage: undefined;
  ScheduleManage_1: undefined | { calendar: string; start: string; end: string };
  ScheduleManage_2: undefined | { modal: boolean; stadiumAddr: string };
  ScheduleManage_3: undefined;
  ScheduleManage_4: undefined;
  ScheduleManage_5: undefined;
  CalendarSelect: undefined | { calendar: string };
  StartTimeSelect: undefined | { start: string };
  EndTimeSelect: undefined | { end: string };
  StadiumSelect: undefined | { modal: boolean; stadiumAddr: string };
  MyPage_Main: undefined;
  NewPhone: undefined;
  NewPhone_1: undefined;
  NewPhone_2: undefined | { phone: string };
  MyProfile: undefined;
  MyProfile_1: undefined | { gender: string };
};
