export type RootStackParamList = {
  Home: undefined;
  AddOns_1: undefined;
  AddOns_2: undefined;
  AddOns_3: undefined | { bank: string };
  MyPage: undefined;
  Lobby: undefined;
  TeamSelect: undefined;
  CreateTeam: undefined;
  CreateTeam_1: undefined;
  CreateTeam_2: undefined;
  CreateTeam_3: undefined | { bank: string };
  CreateTeam_4: undefined;
  CreateTeam_5: undefined | { inviteCode: string };
  CreateTeam_6: undefined;
  BankSelect: { name: keyof RootStackParamList };
  LendingPage: undefined;
  LendingPage_1: undefined;
  LendingPage_2: undefined;
  LendingPage_3: undefined;
  LendingPage_4: undefined;
  LendingPage_5: undefined;
  LendingPage_6: undefined;
  LendingPage_7: undefined;
  LendingPage_8: undefined;
  JoinTeam: undefined;
  JoinTeam_1: undefined | { reset: boolean };
  JoinTeam_2: undefined;
  JoinTeam_3: undefined;
  GetStarted: undefined;
  GetStarted_1: undefined;
  GetStarted_2: undefined;
  GetStarted_3: undefined | { phone: string };
  GetStarted_4: undefined;
  GetStarted_5: undefined | { gender: string };
  GetStarted_6: undefined | { accessToken: string };
  GenderSelect: undefined | { screenName: keyof RootStackParamList };
  GetStarted_Login: undefined | { email: string; name: string };
  ScheduleManage: undefined;
  ScheduleManage_1: undefined | { date: string; startTime: string; endTime: string };
  ScheduleManage_2: undefined | { modal: boolean; stadiumAddr: string };
  ScheduleManage_3: undefined;
  ScheduleManage_4: undefined;
  ScheduleManage_5: undefined;
  CalendarSelect: undefined | { date: string };
  StartTimeSelect: undefined | { startTime: string };
  EndTimeSelect: undefined | { endTime: string };
  StadiumSelect: undefined | { modal: boolean; stadiumAddr: string };
  ChangePassword: undefined | { screenName?: keyof RootStackParamList };
  FindPassword: undefined | { screenName?: keyof RootStackParamList };
  FindPassword_1: undefined | { screenName?: keyof RootStackParamList };
  FindPassword_2: undefined | { screenName?: keyof RootStackParamList };
  MyPage_Main: undefined;
  NewPhone: undefined;
  NewPhone_1: undefined;
  NewPhone_2: undefined | { phone: string };
  MyProfile: undefined;
  MyProfile_1: undefined | { gender: string };
  MatchVote: undefined;
  MatchVote_1: undefined;
  MatchVote_2: undefined;
  MatchVote_3: undefined;
  MatchVote_4: undefined;
  MatchVote_5: undefined;
  MatchVote_6: undefined;
  MercenaryInvite: undefined;
  MercenaryInvite_1: undefined;
  MercenaryInvite_2: undefined;
  MercenaryInvite_3: undefined;
  MercenaryInvite_4: undefined;
  MercenaryInvite_5: undefined;
  CustomerService: undefined;
  CustomerSerice_1: undefined;
  LogOutSelect: undefined;
  DeleteAccount_1: undefined;
  DeleteAccount_2: undefined;
};
