export type RootStackParamList = {
  Home: undefined;
  MyPage: undefined;
  Lobby: undefined;
  TeamSelect: undefined;
  CreateTeam: undefined;
  CreateTeam_1: undefined;
  CreateTeam_2: undefined;
  CreateTeam_3: undefined | { bank: string };
  CreateTeam_4: undefined;
  CreateTeam_5: undefined;
  CreateTeam_6: undefined;
  BankSelect: undefined;
  JoinTeam: undefined;
  JoinTeam_1: undefined | { reset: boolean };
  JoinTeam_2: undefined;
  JoinTeam_3: undefined;
  GetStarted: undefined;
  GetStarted_1: undefined;
  GetStarted_2: undefined;
  GetStarted_3: undefined | { phone: string };
  GetStarted_4: undefined;
};
