export const fontsToLoad = [
  { 'SpoqaHanSansNeo-Bold': require('./fonts/SpoqaHanSansNeo-Bold.otf') },
  { 'SpoqaHanSansNeo-Light': require('./fonts/SpoqaHanSansNeo-Light.otf') },
  { 'SpoqaHanSansNeo-Medium': require('./fonts/SpoqaHanSansNeo-Medium.otf') },
  { 'SpoqaHanSansNeo-Regular': require('./fonts/SpoqaHanSansNeo-Regular.otf') },
  { 'SpoqaHanSansNeo-Thin': require('./fonts/SpoqaHanSansNeo-Thin.otf') },
];

export const imagesToLoad = [
  require('./images/arrow_back_ios.png'),
  require('./images/arrow_back.png'),
  require('./images/arrow_forward_ios.png'),
  require('./images/big-logo.png'),
  require('./images/check-big.png'),
  require('./images/Check.png'),
  require('./images/Checkbox-Blank.png'),
  require('./images/Checkbox.png'),
  require('./images/circle-close-filled.png'),
  require('./images/Circle-filled.png'),
  require('./images/circle-more-horiz.png'),
  require('./images/Circle-Outline.png'),
  require('./images/Circle.png'),
  require('./images/Close-Outline.png'),
  require('./images/Close.png'),
  require('./images/copy.png'),
  require('./images/down.png'),
  require('./images/font-logo.png'),
  require('./images/info.png'),
  require('./images/Line-Active.png'),
  require('./images/line-inactive.png'),
  require('./images/menu-new.png'),
  require('./images/menu.png'),
  require('./images/Minus-Checkbox.png'),
  require('./images/more_horiz.png'),
  require('./images/more_vert.png'),
  require('./images/org-btn.png'),
  require('./images/person.png'),
  require('./images/Plus.png'),
  require('./images/Radio-Blank.png'),
  require('./images/Radio.png'),
  require('./images/remove_red_eye.png'),
  require('./images/search.png'),
  require('./images/settings.png'),
  require('./images/small-logo.png'),
];
